/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import middleware.Utils;

/**
 *
 * @author patri
 */
public class DesktopLogin extends javax.swing.JFrame {

    /**
     * Creates new form DesktopLogin
     */
    public DesktopLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNickname = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        rbtnBlue = new javax.swing.JRadioButton();
        rbtnRed = new javax.swing.JRadioButton();
        rbtnGreen = new javax.swing.JRadioButton();
        rbtnPurple = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Login");

        lblNickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNickname.setText("Nickname:");

        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });

        lblColor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblColor.setText("Color:");

        buttonGroup1.add(rbtnBlue);
        rbtnBlue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnBlue.setForeground(new java.awt.Color(0, 153, 255));
        rbtnBlue.setText("blue");
        rbtnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBlueActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnRed);
        rbtnRed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnRed.setForeground(new java.awt.Color(255, 0, 0));
        rbtnRed.setText("red");
        rbtnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnGreen);
        rbtnGreen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnGreen.setForeground(new java.awt.Color(0, 204, 51));
        rbtnGreen.setText("green");
        rbtnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGreenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnPurple);
        rbtnPurple.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnPurple.setForeground(new java.awt.Color(153, 0, 255));
        rbtnPurple.setText("purple");
        rbtnPurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPurpleActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColor)
                        .addGap(46, 46, 46)
                        .addComponent(rbtnBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnGreen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnPurple))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNickname)
                        .addGap(18, 18, 18)
                        .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLogin)
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(104, 104, 104)))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNickname)
                    .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(rbtnBlue)
                    .addComponent(rbtnRed)
                    .addComponent(rbtnGreen)
                    .addComponent(rbtnPurple))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
    }//GEN-LAST:event_txtNicknameActionPerformed

    private void rbtnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBlueActionPerformed
    }//GEN-LAST:event_rbtnBlueActionPerformed

    private void rbtnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRedActionPerformed
    }//GEN-LAST:event_rbtnRedActionPerformed

    private void rbtnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGreenActionPerformed
    }//GEN-LAST:event_rbtnGreenActionPerformed

    private void rbtnPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPurpleActionPerformed

    }//GEN-LAST:event_rbtnPurpleActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
   
        
            // TODO add your handling code here:
            if(txtNickname.getText() != null){
               Utils.setNickname(txtNickname.getText());
            }

            System.out.print(Utils.getNickname());
            if(rbtnBlue.isSelected()){
                Utils.setColor(rbtnBlue.getText());
                System.out.print(Utils.getColor());
            }
            else if(rbtnRed.isSelected()){
                Utils.setColor(rbtnRed.getText());
                System.out.print(Utils.getColor());
            }
            else if(rbtnGreen.isSelected()){
                Utils.setColor(rbtnGreen.getText());
                System.out.print(Utils.getColor());
            }
            else if(rbtnPurple.isSelected()){
                Utils.setColor(rbtnPurple.getText());
                System.out.print(Utils.getColor());
            }
            
            new DesktopClient().setVisible(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopLogin().setVisible(true);
              
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JRadioButton rbtnBlue;
    private javax.swing.JRadioButton rbtnGreen;
    private javax.swing.JRadioButton rbtnPurple;
    private javax.swing.JRadioButton rbtnRed;
    private javax.swing.JTextField txtNickname;
    // End of variables declaration//GEN-END:variables
}
